### ISSUE TITLE
Initial startup (missing eh.ini) halts due to missing file

### ISSUE THREAD

**Issue by roaet** [roaet/eh#7]
When creating the default configuration (by copying from the default) it fails to find the file and prevents startup.

```
Traceback (most recent call last):
  File "/Users/justin.hammond/Library/Python/3.7/bin/eh", line 10, in <module>
    sys.exit(main())
  File "/Users/justin.hammond/Library/Python/3.7/lib/python/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/justin.hammond/Library/Python/3.7/lib/python/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/justin.hammond/Library/Python/3.7/lib/python/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/justin.hammond/Library/Python/3.7/lib/python/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/justin.hammond/Library/Python/3.7/lib/python/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/justin.hammond/Library/Python/3.7/lib/python/site-packages/eh/cli.py", line 54, in main
    conf = config.open_config()
  File "/Users/justin.hammond/Library/Python/3.7/lib/python/site-packages/eh/config.py", line 19, in open_config
    constants.CONF_FILE)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/justin.hammond/Library/Python/3.7/lib/python/site-packages/eh/../default_conf.ini'
```

**Comment by roaet** [comment]
Fixed in version 1.4.3
